version: '3.8'

services:
  web:
    build: .
    ports:
      - 8000:8000
    volumes:
      - .:/app
    environment:
      GOOGLE_APPLICATION_CREDENTIALS_JSON: "${GOOGLE_APPLICATION_CREDENTIALS_JSON}"
      SENDER_EMAIL: "${SENDER_EMAIL}"
      SENDER_PASSWORD: "${SENDER_PASSWORD}"
